### ISSUE TITLE
The column names in "Initialize Parameters" can't not update, even if I upload my .csv file?

### ISSUE THREAD

**Issue by zhoujj2013** [nasqar/ClusterProfShinyGSEA#1]
Hi Nasqar,

I tried to deploy ClusterProfShinyGSEA to my server, but I came across a problem. 
The column names in "Initialize Parameters" can't not update, even if I upload my .csv file?
Could you please help me with this problem?

Thanks a lot.
Best regards,

Jiajian ZHOU
PhD.

![image](https://user-images.githubusercontent.com/2010005/80936342-604e1f00-8e03-11ea-99f0-a1858ed63f05.png)

**Comment by aymanm** [comment]
Hi,
This is an issue with versions of some of the imported libraries. Try the following:
  
devtools::install_github('rstudio/htmltools')
devtools::install_github('rstudio/shiny')
devtools::install_github('daattali/shinycssloaders')

Let me know if this does not resolve the problem.

**Comment by zhoujj2013** [comment]
Thanks, Nasqar.
It works.
